### 입력 변수 선언 및 전처리

In [22]:
import numpy as np
num = int(input()) #총 몇 명이 피구에 참가할 것인가?
S = np.array([]) #능력치 행렬

for i in range(num):
    s_list = np.array(input().split())
    S = np.append(S, s_list)

#일렬로 쭉 늘어져 저장되기 때문에 reshpe를 통해 2차원 행렬 형태로 재배열
S = S.reshape(num, num)
#string으로 받았기 때문에 int로 형변환 (알아서 원소 각각에 대해 형변환 해 줌.)
S = S.astype(int) 

 5
 0 3 1 1 1
 3 0 1 1 1
 1 1 0 1 1
 1 1 1 0 1
 1 1 1 1 0


[[0 3 1 1 1]
 [3 0 1 1 1]
 [1 1 0 1 1]
 [1 1 1 0 1]
 [1 1 1 1 0]]


### 가능한 모든 조합 만들기

In [23]:
from itertools import combinations
import math

num_list = np.array([]) #플레이어의 idx를 담고 있는 행렬
for i in range(num):
    num_list = np.append(num_list, i)

num_list = num_list.astype(int).astype(str)

cb_list = [] #모든 조합의 경우를 담고 있는 행렬
cb_length = math.ceil(num/2)
for i in np.arange(1, cb_length+1):
    cb_list.append(list(combinations(num_list, i)))

num_list :  ['0' '1' '2' '3' '4']
cb_length :  3


[[('0',), ('1',), ('2',), ('3',), ('4',)],
 [('0', '1'),
  ('0', '2'),
  ('0', '3'),
  ('0', '4'),
  ('1', '2'),
  ('1', '3'),
  ('1', '4'),
  ('2', '3'),
  ('2', '4'),
  ('3', '4')],
 [('0', '1', '2'),
  ('0', '1', '3'),
  ('0', '1', '4'),
  ('0', '2', '3'),
  ('0', '2', '4'),
  ('0', '3', '4'),
  ('1', '2', '3'),
  ('1', '2', '4'),
  ('1', '3', '4'),
  ('2', '3', '4')]]

### 각 조합별 스코어 계산

In [24]:
def synergy_calculator(t, S):
    s = 0
    if len(t) == 1:
        return s
    
    else:
        t_list = list(permutations(t, 2))
        for r in range(len(t_list)):
            i = int(t_list[r][0])
            j = int(t_list[r][1])
            s += S[i][j]
        return s

In [25]:
from itertools import permutations 

Score = []

for i in range(len(cb_list)):
    for j in range(len(cb_list[i])):
        #각 t1, t2의 멤버를 반환받은 후
        t1 = list(cb_list[i][j]) #team1의 멤버
        t2 = list(set(num_list) - set(cb_list[i][j])) #team2의 멤버

        #시너지 스코어를 계산
        s1 = synergy_calculator(t1, S)
        s2 = synergy_calculator(t2, S)
        
        Score.append(abs(s1-s2))
    
print(min(Score))
        

t1 :  ['0']
t2 :  ['2', '1', '4', '3']
zero shape, return 0
t_list :  [('2', '1'), ('2', '4'), ('2', '3'), ('1', '2'), ('1', '4'), ('1', '3'), ('4', '2'), ('4', '1'), ('4', '3'), ('3', '2'), ('3', '1'), ('3', '4')]
S :  1
S :  1
S :  1
S :  1
S :  1
S :  1
S :  1
S :  1
S :  1
S :  1
S :  1
S :  1
s1, s2 :  0 12
t1 :  ['1']
t2 :  ['2', '0', '4', '3']
zero shape, return 0
t_list :  [('2', '0'), ('2', '4'), ('2', '3'), ('0', '2'), ('0', '4'), ('0', '3'), ('4', '2'), ('4', '0'), ('4', '3'), ('3', '2'), ('3', '0'), ('3', '4')]
S :  1
S :  1
S :  1
S :  1
S :  1
S :  1
S :  1
S :  1
S :  1
S :  1
S :  1
S :  1
s1, s2 :  0 12
t1 :  ['2']
t2 :  ['0', '1', '4', '3']
zero shape, return 0
t_list :  [('0', '1'), ('0', '4'), ('0', '3'), ('1', '0'), ('1', '4'), ('1', '3'), ('4', '0'), ('4', '1'), ('4', '3'), ('3', '0'), ('3', '1'), ('3', '4')]
S :  3
S :  1
S :  1
S :  3
S :  1
S :  1
S :  1
S :  1
S :  1
S :  1
S :  1
S :  1
s1, s2 :  0 16
t1 :  ['3']
t2 :  ['2', '0', '4', '1']
zero shape, return 