In [9]:
import numpy as np

def tile(bprint, row, col):
    
    cont = np.zeros((row, col)).astype(int)

    for i in np.arange(row-1):
        for j in np.arange(col-1):
            if bprint[i][j] == 1:
                if bprint[i][j+1] == bprint[i+1][j] and bprint[i+1][j] == bprint[i+1][j+1]:
                    cont[i][j] = -1 
                    cont[i][j+1] = -1
                    cont[i+1][j] = -1
                    cont[i+1][j+1] = -1
    

    res = bprint + cont
    for i in range(len(res)):
        for j in range(len(res[i])):
            if res[i][j] == 1:
                return "NO"
    return "YES"

In [10]:
# task = int(input())
result = []
task = int(input())

for i in range(task):
    row, col = input().split()
    row = int(row)
    col = int(col)
    bprint = np.array([])
    for j in range(row):
        bprint = np.append(bprint, list(input().split()))
    bprint = bprint.reshape(row, col).astype(int)
    result.append(tile(bprint, row, col))

    
for i in range(task):
    print(result[i])

 2
 2 2
 1 0
 0 1
 2 2
 1 1
 1 1


NO
YES


In [10]:
bprint

[['1', '0', '1', '1'],
 ['1', '1', '1', '1'],
 ['1', '1', '0', '0'],
 ['1', '0', '1', '1']]

In [13]:
cont = []
for i in range(4):
    cont.append([0 for _ in range(4)])
cont

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]

In [15]:

bprint = [int (i) for i in row]
bprint + cont

TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

In [ ]:
bprint + np.zeros((4, 4))

In [ ]:
bprint[0][0]

In [ ]:
bprint

In [ ]:
t()

In [ ]:
row, col

In [ ]:
temp = []
temp.append(list(input().split()))

In [ ]:
temp

In [16]:
temp1 = [1, 2, 3, 4]
temp2 = [0, 1, 1, 1]
temp1 + temp2

[1, 2, 3, 4, 0, 1, 1, 1]

In [17]:
temp1 = np.array([1, 2, 3])
tem2 = np.array([2, 2, 3])
temp1 + tem2

array([3, 4, 6])

In [ ]:
bprint = np.append(bprint, list(input().split()))


In [39]:
temp1 = np.array([])

In [43]:
temp1 = np.append(temp1, [1, 2, 3, 4])

In [44]:
temp1 = temp1.reshape(4, 4)

In [45]:
temp1

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [46]:
cont

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]

In [47]:
temp1 + cont

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [54]:
temp1.astype(int)

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])